### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by SanaTameem** [Christelle-12/Capstone-project-1#2]
### Hi @Christelle-12 👋🏻 
You have done a good job so far.
But there are still some issues that you should fix them.♻️ 
![soClose](https://user-images.githubusercontent.com/71990110/227131143-448844a5-d14a-43ae-b35d-331a337631f3.gif)

- It would be better to use `HTML` semantic tags for the `HTML` best practices:
- Try to add your `div ` inside of a `section `tag
https://github.com/Christelle-12/Capstone-project-1/blob/846f6a2ff4a99396bd4ecced505acd745cfbf287/index.html#L74-L94

**Comment by Bellagirl-maker** [comment]
@Christelle-12 Kindly include a <header> tag in your navbar for best HTML practice. So you navbar should be in a header tag.

**Comment by Christelle-12** [comment]
Thank you😊 for the feedback I took care of it.
